---
title: "R Notebook"
output: html_notebook
---

#Color scores
```{r}
b<-read.csv("/Users/imkri/Desktop/Penn Postdoc/Hawaii/allyears2022_Elisa_April 2023.csv", strip.white=T)
b$Date<- as.Date(b$Date, format = "%m/%d/%y")
b$Species<-as.factor(b$Species)
b$Bleach<-as.factor(b$Bleach)
b$ColonyID<-as.factor(b$ColonyID)
b
```
```{r}
unique(b$Date)
```
```{r}
library(lubridate)
library(dplyr)
b$day <- day(as.POSIXlt(b$Date))
b$month <- month(as.POSIXlt(b$Date))
b$year <- year(as.POSIXlt(b$Date))
b$year<-as.factor(b$year)
b<-b%>%
  mutate(season= ifelse(month %in% c(5,6,7,8,9,10), "summer",
                         ifelse(month %in% c(11,12,1,2,3,4), "winter", NA)))%>%
  mutate(period= ifelse(year %in% c(2015) & month %in% c(9,10,11,12), "A",
                               ifelse(year %in% c(2016) & month %in% c(1,2,3,4), "A",
                               ifelse(year %in% c(2016) & month %in% c(5,6,7,8,9,10,11,12), "B",
                               ifelse(year %in% c(2017) & month %in% c(1,2,3,4), "B",
                               ifelse(year %in% c(2017) & month %in% c(5,6,7,8,9,10,11,12), "C",
                               ifelse(year %in% c(2018) & month %in% c(1,2,3,4), "C",
                               ifelse(year %in% c(2018) & month %in% c(5,6,7,8,9,10,11,12), "D",
                               ifelse(year %in% c(2019) & month %in% c(1,2,3,4), "D",
                               ifelse(year %in% c(2019) & month %in% c(5,6,7,8,9,10,11,12), "E",
                               ifelse(year %in% c(2020) & month %in% c(1,2,3,4), "E",
                               ifelse(year %in% c(2020) & month %in% c(5,6,7,8,9,10,11,12), "F",
                               ifelse(year %in% c(2021) & month %in% c(1,2,3,4), "F",
                               ifelse(year %in% c(2021) & month %in% c(5,6,7,8,9,10,11,12),"G",
                               ifelse(year %in% c(2022) & month %in% c(1,2,3,4), "G",
                               ifelse(year %in% c(2022) & month %in% c(5,6,7,8,9,10,11,12),"H",NA))))))))))))))))
b
```


```{r}
library(nlme)
library(car)
b.lm<- lm(Score~Bleach*Species*season*period, data=b, na.action = na.exclude)
Anova(b.lm)
library(emmeans)
tukey<- emmeans(b.lm, list(pairwise ~ Species:Bleach:season:period), adjust = "tukey", simple="Species")
#pairs(bleach.lm)
tukey
```


```{r}
library(Rmisc)
bsum<-summarySE(b, measurevar="Score", groupvars=c("Date","Species","Bleach"), na.rm=TRUE)
bsum
```

```{r}
unique(bsum$Date)
```

###Data exploration
```{r}
library(ggplot2)
bsum$Date<- as.Date(as.POSIXct(bsum$Date, origin="1970-01-01"))
colorfig<-ggplot(bsum, aes(y=Score, x=Date, color=Bleach, fill=Bleach, group=interaction(Species,Bleach)))+ 
  #geom_point(data=b, aes(y=Score,x=Date, color=Bleach),alpha=0.8,position=position_jitterdodge())+
  #geom_smooth(method="loess")+
  #geom_ribbon(aes(ymin=Score-se, ymax=Score+se), alpha=0.4, colour = NA)+
  geom_path(aes(group = interaction(Species,Bleach), stat="identity"), position=position_dodge(0.6))+
  facet_wrap(~Species, nrow=2)+
  #scale_shape_manual("Species", values=c("Bleach"=(pch=8),"Non-bleach"=(pch=16)))+ #Manually choose the colors  
  geom_point(size=3, position=position_dodge(width=0.5),stat="identity", color="black",pch=21)+
  geom_linerange(aes(ymin=Score-se, ymax=Score+se, width= 0.5)) +
  scale_y_continuous(expression(Bleaching~score), limits=c(1,5))+ 
  scale_x_date(limits=as.Date(c("2015-06-01","2023-06-02")),date_breaks = "1 year", date_labels = "%Y",expand=c(0.015,0.015))+
  scale_color_manual("Bleach", values=c("Bleach"= '#DFD3B9',"Non-bleach"='#796334'))+ #Manually choose the colors
  scale_fill_manual("Bleach", values=c("Bleach"= '#DFD3B9',"Non-bleach"='#796334'))+ #Manually choose the colors
  theme_classic()+
  theme(axis.text.x=element_text( vjust=0.5, size=12),
        axis.text.y=element_text(vjust=0.5, size=12),
        axis.title.x=element_blank(),
        axis.title.y=element_text(size=12),
        legend.text = element_text(vjust=0.5, size=12),
        legend.position=c(0.87,0.30),
        panel.background= element_rect(fill=NA, color='black'),
        strip.text = element_text(vjust=0.5, size=12, face="italic"))
colorfig
```
```{r}
library(ggplot2)
bsum$Date<- as.Date(as.POSIXct(bsum$Date, origin="1970-01-01"))
colorfig_colony<-ggplot(b, aes(y=Score, x=Date, color=Bleach, fill=Bleach, group=interaction(Species,Bleach,ColonyID)))+ 
  #geom_point(data=b, aes(y=Score,x=Date, color=Bleach),alpha=0.8,position=position_jitterdodge())+
  #geom_smooth(method="loess")+
  #geom_ribbon(aes(ymin=Score-se, ymax=Score+se), alpha=0.4, colour = NA)+
  geom_line(aes(group = interaction(Species,Bleach), stat="identity"), position=position_dodge(0.6))+
  geom_point()+
  facet_wrap(~ColonyID, ncol=6)+
  #scale_shape_manual("Species", values=c("Bleach"=(pch=8),"Non-bleach"=(pch=16)))+ #Manually choose the colors  
  #geom_point(size=3, position=position_dodge(width=0.5),stat="identity")+
  #geom_linerange(aes(ymin=Score-se, ymax=Score+se, width= 0.5)) +
  scale_y_continuous(expression(Bleaching~score), limits=c(1,5))+ 
  scale_x_date(limits=as.Date(c("2015-06-01","2023-06-02")),date_breaks = "1 year", date_labels = "%Y",expand=c(0.015,0.015))+
  scale_color_manual("Bleach", values=c("Bleach"= '#DFD3B9',"Non-bleach"='#796334'))+ #Manually choose the colors
  scale_fill_manual("Bleach", values=c("Bleach"= '#DFD3B9',"Non-bleach"='#796334'))+ #Manually choose the colors
  theme_classic()+
  theme(axis.text.x=element_text( vjust=0.5, size=12),
        axis.text.y=element_text(vjust=0.5, size=12),
        axis.title.x=element_blank(),
        axis.title.y=element_text(size=12),
        legend.text = element_text(vjust=0.5, size=12),
        legend.position=c(0.87,0.30),
        panel.background= element_rect(fill=NA, color='black'),
        strip.text = element_text(vjust=0.5, size=12))
colorfig_colony
```
```{r}
library(ggplot2)
bsum$Date<- as.Date(as.POSIXct(bsum$Date, origin="1970-01-01"))
colorfig<-ggplot(bsum, aes(y=Score, x=Date, color=Bleach, fill=Bleach, group=interaction(Species,Bleach)))+ 
  #geom_jitter(data=b, aes(y=Score,x=Date, color=Species,shape=Bleach),alpha=0.8,position=position_jitterdodge())+
  #geom_smooth(method="loess")+
  #geom_ribbon(aes(ymin=Score-se, ymax=Score+se), alpha=0.4, colour = NA)+
  geom_path(aes(group = interaction(Species,Bleach), stat="identity"), position=position_dodge(0.6))+
  facet_wrap(~Species, nrow=2)+
  #scale_shape_manual("Species", values=c("Bleach"=(pch=8),"Non-bleach"=(pch=16)))+ #Manually choose the colors  
  geom_point(size=3, position=position_dodge(width=0.5),stat="identity")+
  geom_linerange(aes(ymin=Score-se, ymax=Score+se, width= 0.5)) +
  scale_y_continuous(expression(Bleaching~score), limits=c(1,5))+ 
  scale_x_date(limits=as.Date(c("2015-06-01","2023-06-02")),date_breaks = "1 year", date_labels = "%Y",expand=c(0.015,0.015))+
  scale_color_manual("Bleach", values=c("Bleach"= '#DFD3B9',"Non-bleach"='#796334'))+ #Manually choose the colors
  scale_fill_manual("Bleach", values=c("Bleach"= '#DFD3B9',"Non-bleach"='#796334'))+ #Manually choose the colors
  theme_classic()+
  theme(axis.text.x=element_text( vjust=0.5, size=12),
        axis.text.y=element_text(vjust=0.5, size=12),
        axis.title.x=element_blank(),
        axis.title.y=element_text(size=12),
        legend.text = element_text(vjust=0.5, size=12),
        legend.position=c(0.87,0.30),
        panel.background= element_rect(fill=NA, color='black'),
        strip.text = element_text(vjust=0.5, size=12, face="italic"))
colorfig
```
```{r}
library(ggplot2)
bsum$Date<- as.Date(as.POSIXct(bsum$Date, origin="1970-01-01"))
colorfig2<-ggplot(bsum, aes(y=Score, x=Date, color=Bleach, fill=Bleach, group=interaction(Species,Bleach)))+ 
  #geom_jitter(data=b, aes(y=Score,x=Date, color=Species,shape=Bleach),alpha=0.8,position=position_jitterdodge())+
  #geom_smooth(method="loess")+
  geom_ribbon(aes(ymin=Score-se, ymax=Score+se), alpha=0.4, colour = NA)+
  geom_path(aes(group = interaction(Species,Bleach), stat="identity"), position=position_dodge(0.6))+
  facet_wrap(~Species, nrow=2)+
  #scale_shape_manual("Species", values=c("Bleach"=(pch=8),"Non-bleach"=(pch=16)))+ #Manually choose the colors  
  geom_point(size=3, position=position_dodge(width=0.5),stat="identity")+
  #geom_errorbar(aes(ymin=Score-se, ymax=Score+se, width= 0.5), position=position_dodge2( preserve = "single"),stat="identity") +
  scale_y_continuous(expression(Bleaching~score), limits=c(1,5))+ 
  scale_x_date(limits=as.Date(c("2015-09-01","2022-09-15")),date_breaks = "1 year", date_labels = "%Y",expand=c(0.015,0.015))+
  scale_color_manual("Bleach", values=c("Bleach"= '#DFD3B9',"Non-bleach"='#796334'))+ #Manually choose the colors
  scale_fill_manual("Bleach", values=c("Bleach"= '#DFD3B9',"Non-bleach"='#796334'))+ #Manually choose the colors
  theme_classic()+
  theme(axis.text.x=element_text( vjust=0.5, size=12),
        axis.text.y=element_text(vjust=0.5, size=12),
        axis.title.x=element_blank(),
        axis.title.y=element_text(size=12),
        legend.text = element_text(vjust=0.5, size=12),
        legend.position=c(0.87,0.30),
        panel.background= element_rect(fill=NA, color='black'),
        strip.text = element_text(vjust=0.5, size=12, face="italic"))
colorfig2
```
```{r}
coloroptions<-cowplot::plot_grid(colorfig,colorfig, nrow=2, align="h", axis = "bt")
coloroptions
```


```{r}
library(cowplot)
colorillustrator<-cowplot::plot_grid(colorfig,colorfig,colorfig, nrow=3, align="h", axis = "bt")
colorillustrator
```

```{r}
library(ggplot2)
bsum$Date<- as.Date(as.POSIXct(bsum$Date, origin="1970-01-01"))
colorfig2<-ggplot(bsum, aes(y=Score, x=Date, color=Species, shape=Bleach, fill=Species, group=interaction(Species,Bleach)))+ 
  #geom_jitter(data=b, aes(y=Score,x=Date, color=Species,shape=Bleach),alpha=0.8,position=position_jitterdodge())+
  #geom_ribbon(aes(ymin=Score-se, ymax=Score+se), alpha=0.4, colour = NA)+
  geom_path(aes(group = interaction(Species,Bleach), stat="identity"), position=position_dodge(0.6))+
  #facet_grid(~Species)+
  scale_shape_manual("Species", values=c("Bleach"=(pch=8),"Non-bleach"=(pch=16)))+ #Manually choose the colors  
  geom_point(size=4, position=position_dodge(width=0.5),stat="identity")+
  #geom_errorbar(aes(ymin=Score-se, ymax=Score+se, width= 0.5), position=position_dodge2( preserve = "single"),stat="identity") +
  scale_y_continuous(expression(Bleaching~score), limits=c(1,5))+ 
  scale_x_date(limits=as.Date(c("2019-01-01","2022-03-15")),date_breaks = "1 year", date_labels = "%Y")+
  scale_color_manual("Species", values=c("Montipora capitata"= '#796334',"Porites compressa"='#A09E41'))+ #Manually choose the colors
  scale_fill_manual("Species", values=c("Montipora capitata"= '#796334',"Porites compressa"='#A09E41'))+ #Manually choose the colors
  theme_classic()+
  theme(axis.text.x=element_text( vjust=0.5, size=12),
        axis.text.y=element_text(vjust=0.5, size=12),
        axis.title.x=element_blank(),
        axis.title.y=element_text(size=12),
        legend.text = element_text(vjust=0.5, size=12),
        legend.position=c(0.87,0.87),
        panel.background= element_rect(fill=NA, color='black'),
        strip.text = element_text(vjust=0.5, size=12, face="italic"))
colorfig2
```

```{r}
bsub<-read.csv("/Users/imkri/Desktop/Penn Postdoc/Hawaii/allyears2022_Elisa_April 2022_sub.csv", strip.white=T)
bsub$Date<- as.Date(bsub$Date, format = "%Y-%m-%d")
bsub$Species<-as.factor(bsub$Species)
bsub$Bleach<-as.factor(bsub$Bleach)
bsub$ColonyID<-as.factor(bsub$ColonyID)
bsub
```
```{r}
unique(bsub$Date)
```


```{r}
library(Rmisc)
bsubsum<-summarySE(bsub, measurevar="Score", groupvars=c("Date","Species","Bleach"), na.rm=TRUE)
bsubsum
```
```{r}
library(ggplot2)
bsum$Date<- as.Date(as.POSIXct(bsum$Date, origin="1970-01-01"))
colorfig<-ggplot(bsubsum, aes(y=Score, x=Date, color=Bleach, group=interaction(Species,Bleach)))+ 
  #geom_jitter(data=b, aes(y=Score,x=Date, color=Bleach),alpha=0.2,position=position_jitterdodge())+
  geom_path(aes(group = interaction(Species,Bleach), stat="identity"), position=position_dodge(0.6))+
  facet_grid(~Species)+
  geom_point(size=3, position=position_dodge(width=0.5),stat="identity")+
  geom_errorbar(aes(ymin=Score-se, ymax=Score+se, width= 0.5), position=position_dodge2( preserve = "single"),stat="identity") +
  scale_y_continuous(expression(Bleaching~score), limits=c(1,5))+ 
  scale_x_date(date_breaks = "3 months", date_labels = "%b %y")+
  scale_color_manual("Bleach", values=c("Bleach"= 'grey',"Non-bleach"= "black"))+
  theme_classic()+
  theme(axis.text.x=element_text(angle=90, vjust=0.5, size=12),
        axis.text.y=element_text(vjust=0.5, size=12),
        axis.title.x=element_blank(),
        axis.title.y=element_text(size=12),
        legend.text = element_text(vjust=0.5, size=12),
        legend.position=c(0.87,0.87),
        panel.background= element_rect(fill=NA, color='black'),
        strip.text = element_text(vjust=0.5, size=12, face="italic"))
colorfig
```


###Data manipulation
```{r}
library(lubridate)
library(dplyr)
#grouping each June-March; Jan-Mar "recovery"; June to June calendar year; heat stress (date when it falls below MMM) define this as recovery; bleaching remains Jan/Feb
bsub$day <- day(as.POSIXlt(bsub$Date))
bsub$month <- month(as.POSIXlt(bsub$Date))
bsub$year <- year(as.POSIXlt(bsub$Date))
bsub$year<-as.factor(bsub$year)
bsub<-bsub%>%
  mutate(season= ifelse (month %in% c(5,6,7,8,9,10), "summer",
                         ifelse(month %in% c(11,12,1,2,3,4), "winter", NA))) %>%
  mutate(period= ifelse(year %in% c(2019) & month %in% c(9,10,11,12), "H",
                         ifelse(year %in% c(2019) & month %in% c(5,6,7,8), "A",
                                 ifelse(year %in% c(2020) & month %in% c(1,2,3,4), "A",
                                 ifelse(year %in% c(2020) & month %in% c(5,6,7,8,9,10,11,12), "B",
                                 ifelse(year %in% c(2021) & month %in% c(1,2,3,4), "B",
                                 ifelse(year %in% c(2021) & month %in% c(5,6,7,8,9,10,11,12),"C",
                                 ifelse(year %in% c(2022) & month %in% c(1,2,3,4), "C",NA))))))))
bsub
```
```{r}
unique(bsub$Date)
```
```{r}
library(dplyr)
#bsub<-b%>%
  #dplyr::filter(month==c("10"))
#bsub
```

```{r}
unique(bsub$year)
unique(bsub$period)
```
###Statistics
```{r}
library(nlme)
library(car)
bleach.lm<- lm(Score~Bleach*Species*season*Date, data=bsub, na.action = na.exclude)
Anova(bleach.lm, type=3)
library(emmeans)
tukey<- emmeans(bleach.lm, list(pairwise ~ Bleach:Species:season), adjust = "tukey", simple="season")
#pairs(bleach.lm)
tukey
```

```{r}
summary(b.lm)
r.squaredGLMM(b.lm)
```

```{r}
library(Rmisc)
bsum2<-summarySE(bsub, measurevar="Score", groupvars=c("period","season","Species","Bleach"), na.rm=TRUE)
bsum2
```
###Figure
```{r}
library(ggplot2)
colorfig2<-ggplot(data=subset(bsum2, !is.na(period)), aes(y=Score, x=period, color=Bleach, shape=season, group=interaction(Species,Bleach, period)))+ 
  #geom_jitter(data=b, aes(y=Score,x=period, color=Bleach),alpha=0.6,position=position_jitterdodge())+
  geom_path(aes(group = interaction(Bleach,season), stat="identity"), position=position_dodge(0.3))+
  facet_grid(~Species)+
  geom_point(size=3, position=position_dodge(width=0.3),stat="identity")+
  geom_errorbar(aes(ymin=Score-se, ymax=Score+se, width= 0.5), position=position_dodge(width=0.3),stat="identity") +
  scale_y_continuous(expression(Bleaching~score), limits=c(1,5))+ 
  scale_x_discrete(breaks=c("A", "B","C", "D"), labels=c("2015-2016","2019-2020","2020-2021", "2021-2022"))+
  scale_color_manual("Bleach", values=c("Bleach"= 'grey',"Non-bleach"= "black"))+
  scale_shape_manual("season", values=c(8,19))+
  theme_classic()+
  theme(axis.text.x=element_text(vjust=0.5, size=12),
        axis.text.y=element_text(vjust=0.5, size=12),
        axis.title.x=element_blank(),
        axis.title.y=element_text(size=12),
        legend.text = element_text(vjust=0.5, size=12),
        legend.position=c(0.87,0.65),
        panel.background= element_rect(fill=NA, color='black'),
        strip.text = element_text(vjust=0.5, size=12, face="italic"))
colorfig2
```

#Mortality by Katie 2015-2023

```{r}
m<-read.csv("/Users/imkri/Desktop/Penn Postdoc/Hawaii/KBay pairs mortality 2015-2023.csv", strip.white=T)
#m$Date<- as.Date(m$Date, format = "%Y-%m-%d")
m$Species<-as.factor(m$Species)
m$Phenotype<-as.factor(m$Phenotype)
m$Colony.ID<-as.factor(m$Colony.ID)
m
```
```{r}
colnames(m)
```

```{r}
library(tidyr)
m.long <- pivot_longer(m, cols=5:19, names_to = "Date", values_to = "Mortality")
m.long
```

```{r}
#write.csv(m.long,"Mortality data Kristen.csv")
```

```{r}
m<-read.csv("/Users/imkri/Desktop/Penn Postdoc/Hawaii/Mortality data Kristen.csv", strip.white=T)
#m$Date<- as.Date(m$Date, format = "%Y-%m-%d")
m$Species<-as.factor(m$Species)
m$Phenotype<-as.factor(m$Phenotype)
m$Colony.ID<-as.factor(m$Colony.ID)
m$Date<-as.factor(m$Date)
m
```

###Statistics
```{r}
library(nlme)
library(car)
mort.lme<- lme(Mortality~Phenotype*Species*Date, random = ~1|Colony.ID, data=m, na.action = na.exclude)
Anova(mort.lme, type=3)
library(emmeans)
tukey<- emmeans(mort.lme, list(pairwise ~ Species:Date), adjust = "tukey", simple="Species")
#pairs(mort.lm)
tukey
```

```{r}
summary(mort.lme)
r.squaredGLMM(mort.lme)
```

```{r}
library(Rmisc)
msum<-summarySE(m, measurevar="Mortality", groupvars=c("Date","Species","Phenotype"), na.rm=TRUE)
msum$year <- year(as.POSIXlt(msum$Date))
msum
```

```{r}
msum2<-summarySE(msum, measurevar="Mortality", groupvars=c("Species","Phenotype","year"), na.rm=TRUE)
msum2
```


###Figure
```{r}
library(ggplot2)
msum$Date<- as.Date(as.POSIXct(msum$Date, origin="1970-01-01"))
mortfig<-ggplot(msum, aes(y=Mortality, x=Date, color=Phenotype, fill=Phenotype, group=interaction(Species,Phenotype)))+ 
  #geom_point(data=b, aes(y=Score,x=Date, color=Phenotype),alpha=0.8,position=position_jitterdodge())+
  #geom_smooth(method="loess")+
  #geom_ribbon(aes(ymin=Score-se, ymax=Score+se), alpha=0.4, colour = NA)+
  geom_path(aes(group = interaction(Species,Phenotype), stat="identity"), position=position_dodge(0.6))+
  facet_wrap(~Species, nrow=2)+
  #scale_shape_manual("Species", values=c("Phenotype"=(pch=8),"Non-Phenotype"=(pch=16)))+ #Manually choose the colors  
  geom_point(size=3, position=position_dodge(width=0.5),stat="identity")+
  geom_linerange(aes(ymin=Mortality-se, ymax=Mortality+se, width= 0.5)) +
  scale_y_continuous(expression(Colony~mortality~("%")))+ 
  scale_x_date(limits=as.Date(c("2015-06-01","2023-06-02")),date_breaks = "1 year", date_labels = "%Y",expand=c(0.015,0.015))+
  scale_color_manual("Phenotype", values=c("Susceptible"= '#DFD3B9',"Resistant"='#796334'))+ #Manually choose the colors
  scale_fill_manual("Phenotype", values=c("Susceptible"= '#DFD3B9',"Resistant"='#796334'))+ #Manually choose the colors
  theme_classic()+
  theme(axis.text.x=element_text( vjust=0.5, size=12),
        axis.text.y=element_text(vjust=0.5, size=12),
        axis.title.x=element_blank(),
        axis.title.y=element_text(size=12),
        legend.text = element_text(vjust=0.5, size=12),
        legend.position=c(0.87,0.30),
        panel.background= element_rect(fill=NA, color='black'),
        strip.text = element_text(vjust=0.5, size=12, face="italic"))
mortfig
```
###Figure
```{r}
library(ggplot2)
msum$Date<- as.Date(as.POSIXct(msum$Date, origin="1970-01-01"))
mortfig2<-ggplot(msum, aes(y=Mortality, x=Date, color=Phenotype, fill=Phenotype,group=interaction(Species,Phenotype)))+ 
  geom_line(size=0.75, alpha=0.8)+
  geom_area(aes(y=Mortality),alpha=0.6,position=position_identity()) +
  #geom_path(aes(group = interaction(Species,Phenotype), stat="identity"), position=position_dodge(0.6))+
  facet_wrap(~Species, nrow=2)+
  #geom_point(size=3, position=position_dodge(width=0.5),stat="identity")+
  #geom_linerange(aes(ymin=Mortality-se, ymax=Mortality+se, width= 0.5)) +
  scale_y_continuous(expression(Colony~mortality~("%")), limits=c(0,100))+ 
  scale_x_date(limits=as.Date(c("2015-06-01","2023-09-15")),date_breaks = "1 year", date_labels = "%Y",expand=c(0.015,0.015))+
 scale_color_manual("Phenotype", values=c("Resistant"='#796334',"Susceptible"= '#DFD3B9'))+ #Manually choose the colors
  scale_fill_manual("Phenotype", values=c("Resistant"='#796334',"Susceptible"= '#DFD3B9'))+ #Manually choose the colors
  theme_classic()+
  theme(axis.text.x=element_text( vjust=0.5, size=12),
        axis.text.y=element_text(vjust=0.5, size=12),
        axis.title.x=element_blank(),
        axis.title.y=element_text(size=12),
        legend.text = element_text(vjust=0.5, size=12),
        legend.position=c(0.87,0.30),
        panel.background= element_rect(fill=NA, color='black'),
        strip.text = element_text(vjust=0.5, size=12, face="italic"))
mortfig2
```
```{r}
mortmonti<-filter(m, Species == "Montipora capitata")
mortporites<-filter(m, Species == "Porites compressa")
```


```{r}
library(ggplot2)
msum$Date<- as.Date(as.POSIXct(msum$Date, origin="1970-01-01"))
mortfig_colony_mcap<-ggplot(mortmonti, aes(y=Mortality, x=Date, color=Phenotype, fill=Phenotype, group=interaction(Species,Phenotype,Colony.ID)))+ 
  #geom_point(data=b, aes(y=Score,x=Date, color=Bleach),alpha=0.8,position=position_jitterdodge())+
  #geom_smooth(method="loess")+
  #geom_ribbon(aes(ymin=Score-se, ymax=Score+se), alpha=0.4, colour = NA)+
  geom_area(aes(y=Mortality),alpha=0.6,position=position_identity()) +
  facet_wrap(~Colony.ID, ncol=6)+
  #scale_shape_manual("Species", values=c("Bleach"=(pch=8),"Non-bleach"=(pch=16)))+ #Manually choose the colors  
  #geom_point(size=3, position=position_dodge(width=0.5),stat="identity")+
  #geom_linerange(aes(ymin=Score-se, ymax=Score+se, width= 0.5)) +
  scale_y_continuous(expression(Colony~mortality~("%")), limits=c(0,100), position="right")+ 
  scale_x_date(limits=as.Date(c("2015-06-01","2023-09-15")),date_breaks = "1 year", date_labels = "%Y",expand=c(0.015,0.015))+
  scale_color_manual("Phenotype", values=c("Resistant"='#796334',"Susceptible"= '#DFD3B9'))+ #Manually choose the colors
  scale_fill_manual("Phenotype", values=c("Resistant"='#796334',"Susceptible"= '#DFD3B9'))+ #Manually choose the colors
  theme_classic()+
  theme(axis.text.x=element_text( vjust=0.5, size=12),
        axis.text.y=element_text(vjust=0.5, size=12),
        axis.title.x=element_blank(),
        axis.title.y=element_text(size=12),
        legend.text = element_text(vjust=0.5, size=12),
        legend.position=c(0.87,0.30),
        panel.background= element_rect(fill=NA, color='black'),
        strip.text = element_text(vjust=0.5, size=12))
mortfig_colony_mcap
```
```{r}
library(ggplot2)
msum$Date<- as.Date(as.POSIXct(msum$Date, origin="1970-01-01"))
mortfig_colony_pcom<-ggplot(mortporites, aes(y=Mortality, x=Date, color=Phenotype, fill=Phenotype, group=interaction(Species,Phenotype,Colony.ID)))+ 
  #geom_point(data=b, aes(y=Score,x=Date, color=Bleach),alpha=0.8,position=position_jitterdodge())+
  #geom_smooth(method="loess")+
  #geom_ribbon(aes(ymin=Score-se, ymax=Score+se), alpha=0.4, colour = NA)+
  geom_area(aes(y=Mortality),alpha=0.6,position=position_identity()) +
  facet_wrap(~Colony.ID, ncol=6)+
  #scale_shape_manual("Species", values=c("Bleach"=(pch=8),"Non-bleach"=(pch=16)))+ #Manually choose the colors  
  #geom_point(size=3, position=position_dodge(width=0.5),stat="identity")+
  #geom_linerange(aes(ymin=Score-se, ymax=Score+se, width= 0.5)) +
  scale_y_continuous(expression(Colony~mortality~("%")), limits=c(0,100), position="right")+ 
  scale_x_date(limits=as.Date(c("2015-06-01","2023-09-15")),date_breaks = "1 year", date_labels = "%Y",expand=c(0.015,0.015))+
  scale_color_manual("Phenotype", values=c("Resistant"='#796334',"Susceptible"= '#DFD3B9'))+ #Manually choose the colors
  scale_fill_manual("Phenotype", values=c("Resistant"='#796334',"Susceptible"= '#DFD3B9'))+ #Manually choose the colors
  theme_classic()+
  theme(axis.text.x=element_text( vjust=0.5, size=12),
        axis.text.y=element_text(vjust=0.5, size=12),
        axis.title.x=element_blank(),
        axis.title.y=element_text(size=12),
        legend.text = element_text(vjust=0.5, size=12),
        legend.position=c(0.87,0.30),
        panel.background= element_rect(fill=NA, color='black'),
        strip.text = element_text(vjust=0.5, size=12))
mortfig_colony_pcom
```
```{r}
mortoptions<-cowplot::plot_grid(mortfig_colony_mcap,mortfig_colony_pcom, nrow=2, align="h", axis = "bt")
mortoptions
```


```{r}
library(ggplot2)
#bsum$Date<- as.Date(as.POSIXct(bsum$Date, origin="1970-01-01"))
mortalityfig<-ggplot(m, aes(y=Mortality, x=Date, color=Phenotype, group=interaction(Species,Phenotype)))+ 
  #geom_jitter(data=b, aes(y=Score,x=Date, color=Bleach),alpha=0.2,position=position_jitterdodge())+
  #geom_path(aes(group = interaction(ColonyID), stat="identity"), position=position_dodge(0.6))+
  facet_wrap(~Species, nrow=2)+
  geom_point(size=3, position=position_dodge(width=0.5),stat="identity")+
  #geom_errorbar(aes(ymin=Scores-se, ymax=Scores+se, width= 0.5), position=position_dodge2( preserve = "single"),stat="identity") +
  scale_y_continuous(expression(Mortality~score))+ 
  #scale_x_date(date_breaks = "3 months", date_labels = "%b %y")+
 scale_color_manual("Phenotype", values=c("Susceptible"= '#DFD3B9',"Resistant"='#796334'))+ #Manually choose the colors
  scale_fill_manual("Phenotype", values=c("Susceptible"= '#DFD3B9',"Resistant"='#796334'))+ #Manually choose the colors
  theme_classic()+
  theme(axis.text.x=element_text(vjust=0.5, size=12),
        axis.text.y=element_text(vjust=0.5, size=12),
        axis.title.x=element_blank(),
        axis.title.y=element_text(size=12),
        legend.text = element_text(vjust=0.5, size=12),
        #legend.position=c(0.87,0.87),
        panel.background= element_rect(fill=NA, color='black'),
        strip.text = element_text(vjust=0.5, size=12, face="italic"))
mortalityfig
```

###Statistics
```{r}
library(nlme)
library(car)
mortality.lm<- lm(Scores~Bleach*Species*Year, data=m, na.action = na.exclude)
Anova(mortality.lm, type=3)
library(emmeans)
tukey<- emmeans(mortality.lm, list(pairwise ~ Species), adjust = "tukey")
tukey
```
```{r}
library(Rmisc)
msum<-summarySE(m, measurevar="Scores", groupvars=c("Species","Bleach", "Year"), na.rm=TRUE)
msum
```
###Figure
```{r}
library(ggplot2)
#bsum$Date<- as.Date(as.POSIXct(bsum$Date, origin="1970-01-01"))
mortalityfig<-ggplot(msum, aes(y=Scores, x=Year, color=Bleach, group=interaction(Species,Bleach)))+ 
  geom_jitter(data=m, aes(y=Scores,x=Year, color=Bleach),alpha=0.6,position=position_jitterdodge())+
  geom_path(aes(group = interaction(Species,Bleach), stat="identity"), position=position_dodge(0.6))+
  facet_grid(~Species)+
  geom_point(size=3, position=position_dodge(width=0.5),stat="identity")+
  geom_errorbar(aes(ymin=Scores-se, ymax=Scores+se, width= 0.5), position=position_dodge2( preserve = "single"),stat="identity") +
  scale_y_continuous(expression(Mortality~score), limits=c(1,3))+ 
  #scale_x_date(date_breaks = "3 months", date_labels = "%b %y")+
  scale_color_manual("Bleach", values=c("Bleach"= 'grey',"Non-bleach"= "black"))+
  theme_classic()+
  theme(axis.text.x=element_text(vjust=0.5, size=12),
        axis.text.y=element_text(vjust=0.5, size=12),
        axis.title.x=element_blank(),
        axis.title.y=element_text(size=12),
        legend.text = element_text(vjust=0.5, size=12),
        legend.position=c(0.87,0.87),
        panel.background= element_rect(fill=NA, color='black'),
        strip.text = element_text(vjust=0.5, size=12, face="italic"))
mortalityfig
```
```{r}
library(cowplot)
mortill<-cowplot::plot_grid(mortalityfig,mortalityfig,mortalityfig, nrow=3, align="h", axis = "bt")
mortill
```

